name: CI Test

on:
  push:
#    branches: [ "main" ]
    branches: [ "kbh" ]
#  schedule:
  # - cron: '00 12 * * *' # UST 가 default. UST 10:00는 한국시간 21:00(9H 차이)
  # - cron: '00 19 * * *' # UST 가 default. UST 19:00는 한국시간 04:00(9H 차이)

jobs:
  runs-on: ubuntu-latest # 최신 우분투 사용

  steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    # 권한
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 빌드 -> 이때는 test 코드 실행 제외
    - name: Build with Gradle
      run: ./gradlew build -x test

    # 테스트 코드 (프로필로 실행)
    - name: Test with Gradle
      run: SPRING_PROFILES_ACTIVE=[test] ./gradlew test

